name: Beyond Real
favicon: null
layout_spectrum: 0.03373
typography_spectrum: 0.49428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1a21'
    - '#224656'
    - '#57a5c3'
    - '#4486a0'
    - '#8fbbd9'
  brandStrength: 0.19746481883339584
  lightness: 0.493349980795756
  saturation: 0.987868484808132
  rhythmicContrast: 0.19376279623247683
purpose: []
